version: "3.8"
services:
  otus-db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat_db
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: